# application.yml
server:
  port: 8080

spring:
  docker:
    compose:
      enabled: false
  flyway:
    enabled: true
    locations: classpath:/migration

event:
  service:
    base-url: http://localhost:8081
